const menu = [
    {
        id: 1,
        name: 'Khoai tây nghiền gà BBQ sốt ngọt',
        calo: 580,
        protein: '31g',
        carb: '67g',
        fat: '18g',
        price: '60',
        detail: {
            'chicken breast': {
                gam: '85g',
                protein: '26.3g',
                fat: '3.1',
                calories: '165',
            },
            potato: {
                gam: '300g',
                carb: '61g',
                protein: '5.6g',
                calories: '261',
            },
            'kewpie sốt mè rang': {
                gam: '40g',
                fat: '14.4',
                calories: '154',
            },
        },
    },
    {
        id: 2,
        name: 'Khoai tây nghiền gà BBQ sốt ngọt',
        calo: 580,
        protein: '31g',
        carb: '67g',
        fat: '18g',
        price: '60',
        detail: {
            'chicken breast': {
                gam: '85g',
                protein: '26.3g',
                fat: '3.1',
                calories: '165',
            },
            potato: {
                gam: '300g',
                carb: '61g',
                protein: '5.6g',
                calories: '261',
            },
            'kewpie sốt mè rang': {
                gam: '40g',
                fat: '14.4',
                calories: '154',
            },
        },
    },
    {
        id: 3,
        name: 'Khoai tây nghiền gà BBQ sốt ngọt',
        calo: 580,
        protein: '31g',
        carb: '67g',
        fat: '18g',
        price: '60',
        detail: {
            'chicken breast': {
                gam: '85g',
                protein: '26.3g',
                fat: '3.1',
                calories: '165',
            },
            potato: {
                gam: '300g',
                carb: '61g',
                protein: '5.6g',
                calories: '261',
            },
            'kewpie sốt mè rang': {
                gam: '40g',
                fat: '14.4',
                calories: '154',
            },
        },
    },
    {
        id: 4,
        name: 'Khoai tây nghiền gà BBQ sốt ngọt',
        calo: 580,
        protein: '31g',
        carb: '67g',
        fat: '18g',
        price: '60',
        detail: {
            'chicken breast': {
                gam: '85g',
                protein: '26.3g',
                fat: '3.1',
                calories: '165',
            },
            potato: {
                gam: '300g',
                carb: '61g',
                protein: '5.6g',
                calories: '261',
            },
            'kewpie sốt mè rang': {
                gam: '40g',
                fat: '14.4',
                calories: '154',
            },
        },
    },
    {
        id: 5,
        name: 'Khoai tây nghiền gà BBQ sốt ngọt',
        calo: 580,
        protein: '31g',
        carb: '67g',
        fat: '18g',
        price: '60',
        detail: {
            'chicken breast': {
                gam: '85g',
                protein: '26.3g',
                fat: '3.1',
                calories: '165',
            },
            potato: {
                gam: '300g',
                carb: '61g',
                protein: '5.6g',
                calories: '261',
            },
            'kewpie sốt mè rang': {
                gam: '40g',
                fat: '14.4',
                calories: '154',
            },
        },
    },
    {
        id: 6,
        name: 'Khoai tây nghiền gà BBQ sốt ngọt',
        calo: 580,
        protein: '31g',
        carb: '67g',
        fat: '18g',
        price: '60',
        detail: {
            'chicken breast': {
                gam: '85g',
                protein: '26.3g',
                fat: '3.1',
                calories: '165',
            },
            potato: {
                gam: '300g',
                carb: '61g',
                protein: '5.6g',
                calories: '261',
            },
            'kewpie sốt mè rang': {
                gam: '40g',
                fat: '14.4',
                calories: '154',
            },
        },
    },
    {
        id: 7,
        name: 'Khoai tây nghiền gà BBQ sốt ngọt',
        calo: 580,
        protein: '31g',
        carb: '67g',
        fat: '18g',
        price: '60',
        detail: {
            'chicken breast': {
                gam: '85g',
                protein: '26.3g',
                fat: '3.1',
                calories: '165',
            },
            potato: {
                gam: '300g',
                carb: '61g',
                protein: '5.6g',
                calories: '261',
            },
            'kewpie sốt mè rang': {
                gam: '40g',
                fat: '14.4',
                calories: '154',
            },
        },
    },
    {
        id: 8,
        name: 'Khoai tây nghiền gà BBQ sốt ngọt',
        calo: 580,
        protein: '31g',
        carb: '67g',
        fat: '18g',
        price: '60',
        detail: {
            'chicken breast': {
                gam: '85g',
                protein: '26.3g',
                fat: '3.1',
                calories: '165',
            },
            potato: {
                gam: '300g',
                carb: '61g',
                protein: '5.6g',
                calories: '261',
            },
            'kewpie sốt mè rang': {
                gam: '40g',
                fat: '14.4',
                calories: '154',
            },
        },
    },
    {
        id: 9,
        name: 'Khoai tây nghiền gà BBQ sốt ngọt',
        calo: 580,
        protein: '31g',
        carb: '67g',
        fat: '18g',
        price: '60',
        detail: {
            'chicken breast': {
                gam: '85g',
                protein: '26.3g',
                fat: '3.1',
                calories: '165',
            },
            potato: {
                gam: '300g',
                carb: '61g',
                protein: '5.6g',
                calories: '261',
            },
            'kewpie sốt mè rang': {
                gam: '40g',
                fat: '14.4',
                calories: '154',
            },
        },
    },
];
